### ISSUE TITLE
CI: Add fast-path options for non-code/non-critical CI jobs

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/ci#192]
**Which feature do you think can be improved?**

Some CI jobs we know can basically skip the CI, but, due to our locked down setup, we currently have to fire a full CI cycle on them. This wastes both time and resource.

**How can it be improved?**

We'd like some method(s) to be able to mark a PR as 'does not need CI', and have it pass the CI as fast as possible, to allow merging.

**Additional Information**

We have a couple of options here. Note, this is to fix whilst Jenkins is using the freestyle jobs - if/when we do this on a Jenkins Pipeline setup, we may do it subtly differently...

- use a `git diff` to find the list of changed files, and check if we only have markdown or txt file changes (see https://github.com/kata-containers/tests/blob/master/.ci/static-checks.sh#L188 for example of file list extraction)
- use a `curl` to pull down the list of labels on the PR, and look for a specific 'skip ci' label:
```bash
json=$(/usr/bin/curl -H \"Authorization: Basic ${GITHUB_API_TOKEN}\" https://api.github.com/repos/${env.ghprbGhRepository}/issues/${env.ghprbPullId}/labels")
```

Reservations I have on the two methods then:
- we will find it hard to define a list of files and file types that can be skipped - we will always find something extra like `LICENSE` or `Versions` that will not be picked out
- some folks are understandably nervous that having the skip label implemented could let anybody submitting a PR skip the CI - and if the reviewers didn't realise, they could merge without it having been tested...

I'll spin a PR, and we can review/discuss

**Comment by jodh-intel** [comment]
This is indeed awkward. I was hoping we'd be able to skip the CI for all PRs that don't touch the following file types:

- `*.go`
- `*.sh`
- `*.yaml`

But there are of course exceptions:

- What if the PR is in the documentation repo and it changes an install doc? They **must** be tested.

There are bound to be other instances too.

I think the ideal would be a YAML file that allows us to encode this "CI skip logic" in a set of regexp's for each repo. If the PR contains any regexp matches, the PR should run the CI.

```yaml
---
generic:
  run-ci:
    - code: >-
        *.go
      description: Golang code.
    - shell: >-
        *.sh
      description: Shell script.
    - config: >-
        *.yaml
      description: YAML configuration files.

repositories:
  documentation:
    run-ci:
      - install-docs: >-
          install/*
        description: |
            Installation documents whose embedded code is tested by the CI.
    ci:
      run-ci:
        - jenkins-config: >-
            *.xml
          description: Jenkins CI configuration files.
```

But we'd always need a way to override this I think. Since labels could potentially be added by anyone, we might need a new magic "`/skip-ci`" comment or similar. That way, "something" like a bot/Jenkins plugin could query the PR using the GitHub API and check for that comment. **Iff** that comment was added by a core team member, the PR would be considered mergeable without a CI run (but only after the normal set of acks have also been applied of course).

**Comment by grahamwhaley** [comment]
I can see having a set of patterns per repo could make sense, and having a generic set to merge with those will reduce duplication.  And inverting the test (things that *must* be tested) might also work. That yaml looks overly complex though. I think we could simplify that a lot, which would make it easier to parse in the scripts as well. 

```yaml
---
generic:
  - .*\.go
  - .*\.sh
  - .*\.yaml

runtime:
  - install/.*
```

We could then *invert* the label, so have a '/must-ci' label that will disable the skip check... that way the worst thing anybody can do with a label is make their PR get CI'd when maybe it did not need to. Reading/checking labels is going to be much easier than trying to scan for comments in a PR I think.

We need to err on the side of 'CI to much' rather than 'CI too little' I think - as I'm pretty sure reviewers will not spot the CIs accidentally skipping on a PR where they should not (and sadly githubs lack of variants of CI status pretty much to yes/no/running does not help us here).

/cc @egernst @chavafg for input.
