### ISSUE TITLE
podman 1.8.2 is not present on Fedora 31 anymore

### ISSUE THREAD

**Issue by fidencio** [kata-containers/ci#271]
# Description of problem

CI cannot install podman-1.8.2 on Fedora 31

# Expected result

Don't rely on a specific podman version.

# Actual result

```
12:25:02 Install podman
12:25:04 Last metadata expiration check: 0:02:30 ago on Fri 17 Apr 2020 10:22:34 AM UTC.
12:25:06 No match for argument: podman-1.8.2
12:25:06 Error: Unable to find a match: podman-1.8.2
12:25:06 Failed at 21: sudo -E dnf -y install podman-"${version}"
12:25:06 Build step 'Execute shell' marked build as failure
```

This opens for a discussion, why do we need 1.8.2?

**Comment by devimc** [comment]
> Don't rely on a specific podman version.

If we don't rely on specific versions, we won't have tests 100% reproducible all the time

**Comment by fidencio** [comment]
> > Don't rely on a specific podman version.
> 
> If we don't rely on specific versions, we won't have tests 100% reproducible all the time

That's quite hard to have, if not impossible, with distros updating their content / images.
I wonder whether building podman from source wouldn't be a better thing to do in this case.

**Comment by devimc** [comment]
> That's quite hard to have, if not impossible, with distros updating their content / images.

yes I agree, but at least we should have control over the major and minor versions, for example install podman 1.8 and not 1.9

> I wonder whether building podman from source wouldn't be a better thing to do in this case.

maybe we should add a new section in the `versions.yaml` for podman

```yaml
  podman:
    description: "Podman project container manager"
    url: "https://podman.io/"
    version: "1.8"
```

**Comment by fidencio** [comment]
> 
> yes I agree, but at least we should have control over the major and minor versions, for example install podman 1.8 and not 1.9

I don't see that happening on Fedora. For instance, in the end it'll boil down to the maintainer shipping a new version of the package, even after a release is out and running.

> 
> maybe we should add a new section in the `versions.yaml` for podman
> 
> ```yaml
>   podman:
>     description: "Podman project container manager"
>     url: "https://podman.io/"
>     version: "1.8"
> ```

What does it mean, exactly?

**Comment by devimc** [comment]
> I don't see that happening on Fedora. For instance, in the end it'll boil down to the maintainer shipping a new version of the package, even after a release is out and running.

ok, then build from source is the plan b (same ad crio and others)

> What does it mean, exactly?

don't hardcode  the version in the scripts and read it form here

**Comment by fidencio** [comment]
> ok, then build from source is the plan b (same ad crio and others)

Unfortunately, yes.

> don't hardcode the version in the scripts and read it form here

I thought so and no, it wouldn't help us as building from souce would be the way to ensure we wouldn't face issues.

More than that, building from sources for every distro we test would actually ensure that we're not relying on downstream patches and whatnot.

**Comment by devimc** [comment]
> I thought so and no, it wouldn't help us as building from souce would be the way to ensure we wouldn't face issues.

yes, but you will need to get the source version from somewhere, this way the update to a new version will easier, even for people that don't write the installation script

**Comment by fidencio** [comment]
> yes, but you will need to get the source version from somewhere, this way the update to a new version will be easier, even for people that don't write the installation script

Aha, yes, you're right! Now I see your point. :-)

**Comment by wainersm** [comment]
> > That's quite hard to have, if not impossible, with distros updating their content / images.
> 
> yes I agree, but at least we should have control over the major and minor versions, for example install podman 1.8 and not 1.9
> 
> > I wonder whether building podman from source wouldn't be a better thing to do in this case.
> 
> maybe we should add a new section in the `versions.yaml` for podman
> 
> ```yaml
>   podman:
>     description: "Podman project container manager"
>     url: "https://podman.io/"
>     version: "1.8"
> ```

Can we use a range of versions just like `golang` in the snippet below (from https://github.com/kata-containers/runtime/versions.yaml)?

So we can have the last-known-to-work version of podman, and a minimum required. Hopefully installing some version in between is acceptable.

```
  golang:
    description: "Google's 'go' language"
    notes: "'version' is the default minimum version used by this project."
    issue: "https://github.com/golang/go/issues/20676"
    uscan-url: >-
      https://github.com/golang/go/tags .*/go?([\d\.]+)\.tar\.gz
    version: "1.11.10"
    meta:
      description: |
        'newest-version' is the latest version known to work when
        building Kata
      newest-version: "1.13.9"
```
